sudo: false
language: node_js
node_js: 8
os:
  - osx
  - linux

install:
  - |
    if [ $TRAVIS_OS_NAME == "linux" ]; then
      export DISPLAY=':99.0'
      /usr/bin/Xvfb :99 -screen 0 1024x768x24 > /dev/null 2>&1 &
    fi
  - npm install

script:
  - npm build
  - npm test:e2e

cache:
  directories:
  - .vscode-test
